### ISSUE TITLE
axum 版本无法编译

### ISSUE THREAD

**Issue by jukanntenn** [lingdu1234/axum_admin#1]
执行的命令：`cargo run --bin axum-admin`

```
error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
   --> /Users/yangxg/.cargo/registry/src/github.com-1ecc6299db9ec823/scru128-2.1.3/src/generator.rs:71:6
    |
71  | impl<R: RngCore> Scru128Generator<R> {
    |      ^
...
164 |     pub const fn last_status(&self) -> Status {
    |     ----------------------------------------- function declared as const here
    |
    = note: see issue #93706 <https://github.com/rust-lang/rust/issues/93706> for more information

For more information about this error, try `rustc --explain E0658`.
```

是否是依赖库的版本问题？

**Comment by lingdu1234** [comment]
nightly-x86_64-pc-windows-msvc unchanged - rustc 1.64.0-nightly (c2f428d2f 2022-07-14)
stable-x86_64-pc-windows-msvc unchanged - rustc 1.62.0 (a8314ef7d 2022-06-27)
升级到1.62.1都没有问题啊，你的环境是什么，我只在windows下测试的

**Comment by lingdu1234** [comment]
按道理，应该是没有问题的  github  的 action 下ubuntu 都可以的
https://github.com/lingdu1234/axum_admin/runs/7427926944

**Comment by jukanntenn** [comment]
谢谢！我是 macOS，一开始 rustc 版本是 1.60，升级到 1.62后好像就可以了。

**Comment by dashing-devtool** [comment]
:87
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library\core\src\panicking.rs:142
   2: core::result::unwrap_failed
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library\core\src\result.rs:1814
   3: enum$<core::result::Result<axum_server::tls_rustls::RustlsConfig,std::io::error::Error> >::unwrap<axum_server::tls_rustls::RustlsConfig,std::io::error::Error>
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235\library\core\src\result.rs:1107
   4: axum_admin::main::async_block$0
             at .\bin\src\main.rs:78
   5: core::future::from_generator::impl$1::poll<enum$<axum_admin::main::async_block_env$0> >
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235\library\core\src\future\mod.rs:91
   6: tokio::park::thread::impl$5::block_on::closure$0<core::future::from_generator::GenFuture<enum$<axum_admin::main::async_block_env$0> > >
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\park\thread.rs:263
   7: tokio::coop::with_budget::closure$0<enum$<core::task::poll::Poll<tuple$<> > >,tokio::park::thread::impl$5::block_on::closure_env$0<core::future::from_generator::GenFuture<enum$<axum_admin::main::async_block_env$0> > > >
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\coop.rs:102
   8: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget> >::try_with<core::cell::Cell<tokio::coop::Budget>,tokio::coop::with_budget::closure_env$0<enum$<core::task::poll::Poll<tuple$<> > >,tokio::park::thread::impl$5::block_on::closure_env$0<cor
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235\library\std\src\thread\local.rs:445
   9: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget> >::with<core::cell::Cell<tokio::coop::Budget>,tokio::coop::with_budget::closure_env$0<enum$<core::task::poll::Poll<tuple$<> > >,tokio::park::thread::impl$5::block_on::closure_env$0<core::f
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235\library\std\src\thread\local.rs:421
  10: tokio::coop::with_budget
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\coop.rs:95
  11: tokio::coop::budget
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\coop.rs:72
  12: tokio::park::thread::CachedParkThread::block_on<core::future::from_generator::GenFuture<enum$<axum_admin::main::async_block_env$0> > >
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\park\thread.rs:263
  13: tokio::runtime::enter::Enter::block_on<core::future::from_generator::GenFuture<enum$<axum_admin::main::async_block_env$0> > >
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\runtime\enter.rs:152
  14: tokio::runtime::thread_pool::ThreadPool::block_on<core::future::from_generator::GenFuture<enum$<axum_admin::main::async_block_env$0> > >
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\runtime\thread_pool\mod.rs:90
  15: tokio::runtime::Runtime::block_on<core::future::from_generator::GenFuture<enum$<axum_admin::main::async_block_env$0> > >
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\runtime\mod.rs:484
  16: axum_admin::main
             at .\bin\src\main.rs:27
  17: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235\library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\axum-admin.exe` (exit code: 101)

**Comment by dashing-devtool** [comment]
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library\core\src\panicking.rs:142
   2: core::result::unwrap_failed
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library\core\src\result.rs:1814
   3: enum$<core::result::Result<axum_server::tls_rustls::RustlsConfig,std::io::error::Error> >::unwrap<axum_server::tls_rustls::RustlsConfig,std::io::error::Error>
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235\library\core\src\result.rs:1107
   4: axum_admin::main::async_block$0
             at .\bin\src\main.rs:78
   5: core::future::from_generator::impl$1::poll<enum$<axum_admin::main::async_block_env$0> >
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235\library\core\src\future\mod.rs:91
   6: tokio::park::thread::impl$5::block_on::closure$0<core::future::from_generator::GenFuture<enum$<axum_admin::main::async_block_env$0> > >
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\park\thread.rs:263
   7: tokio::coop::with_budget::closure$0<enum$<core::task::poll::Poll<tuple$<> > >,tokio::park::thread::impl$5::block_on::closure_env$0<core::future::from_generator::GenFuture<enum$<axum_admin::main::async_block_env$0> > > >
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\coop.rs:102
   8: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget> >::try_with<core::cell::Cell<tokio::coop::Budget>,tokio::coop::with_budget::closure_env$0<enum$<core::task::poll::Poll<tuple$<> > >,tokio::park::thread::impl$5::block_on::closure_env$0<cor
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235\library\std\src\thread\local.rs:445
   9: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget> >::with<core::cell::Cell<tokio::coop::Budget>,tokio::coop::with_budget::closure_env$0<enum$<core::task::poll::Poll<tuple$<> > >,tokio::park::thread::impl$5::block_on::closure_env$0<core::f
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235\library\std\src\thread\local.rs:421
  10: tokio::coop::with_budget
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\coop.rs:95
  11: tokio::coop::budget
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\coop.rs:72
  12: tokio::park::thread::CachedParkThread::block_on<core::future::from_generator::GenFuture<enum$<axum_admin::main::async_block_env$0> > >
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\park\thread.rs:263
  13: tokio::runtime::enter::Enter::block_on<core::future::from_generator::GenFuture<enum$<axum_admin::main::async_block_env$0> > >
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\runtime\enter.rs:152
  14: tokio::runtime::thread_pool::ThreadPool::block_on<core::future::from_generator::GenFuture<enum$<axum_admin::main::async_block_env$0> > >
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\runtime\thread_pool\mod.rs:90
  15: tokio::runtime::Runtime::block_on<core::future::from_generator::GenFuture<enum$<axum_admin::main::async_block_env$0> > >
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\runtime\mod.rs:484
  16: axum_admin::main
             at .\bin\src\main.rs:27
  17: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235\library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\axum-admin.exe` (exit code: 101)

**Comment by dashing-devtool** [comment]
`stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library\core\src\panicking.rs:142
   2: core::result::unwrap_failed
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library\core\src\result.rs:1814
   3: enum$<core::result::Result<axum_server::tls_rustls::RustlsConfig,std::io::error::Error> >::unwrap<axum_server::tls_rustls::RustlsConfig,std::io::error::Error>
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235\library\core\src\result.rs:1107
   4: axum_admin::main::async_block$0
             at .\bin\src\main.rs:78
   5: core::future::from_generator::impl$1::poll<enum$<axum_admin::main::async_block_env$0> >
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235\library\core\src\future\mod.rs:91
   6: tokio::park::thread::impl$5::block_on::closure$0<core::future::from_generator::GenFuture<enum$<axum_admin::main::async_block_env$0> > >
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\park\thread.rs:263
   7: tokio::coop::with_budget::closure$0<enum$<core::task::poll::Poll<tuple$<> > >,tokio::park::thread::impl$5::block_on::closure_env$0<core::future::from_generator::GenFuture<enum$<axum_admin::main::async_block_env$0> > > >
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\coop.rs:102
   8: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget> >::try_with<core::cell::Cell<tokio::coop::Budget>,tokio::coop::with_budget::closure_env$0<enum$<core::task::poll::Poll<tuple$<> > >,tokio::park::thread::impl$5::block_on::closure_env$0<cor
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235\library\std\src\thread\local.rs:445
   9: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget> >::with<core::cell::Cell<tokio::coop::Budget>,tokio::coop::with_budget::closure_env$0<enum$<core::task::poll::Poll<tuple$<> > >,tokio::park::thread::impl$5::block_on::closure_env$0<core::f
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235\library\std\src\thread\local.rs:421
  10: tokio::coop::with_budget
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\coop.rs:95
  11: tokio::coop::budget
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\coop.rs:72
  12: tokio::park::thread::CachedParkThread::block_on<core::future::from_generator::GenFuture<enum$<axum_admin::main::async_block_env$0> > >
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\park\thread.rs:263
  13: tokio::runtime::enter::Enter::block_on<core::future::from_generator::GenFuture<enum$<axum_admin::main::async_block_env$0> > >
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\runtime\enter.rs:152
  14: tokio::runtime::thread_pool::ThreadPool::block_on<core::future::from_generator::GenFuture<enum$<axum_admin::main::async_block_env$0> > >
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\runtime\thread_pool\mod.rs:90
  15: tokio::runtime::Runtime::block_on<core::future::from_generator::GenFuture<enum$<axum_admin::main::async_block_env$0> > >
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\runtime\mod.rs:484
  16: axum_admin::main
             at .\bin\src\main.rs:27
  17: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235\library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\axum-admin.exe` (exit code: 101)`

**Comment by dashing-devtool** [comment]
`
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library\core\src\panicking.rs:142
   2: core::result::unwrap_failed
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235/library\core\src\result.rs:1814
   3: enum$<core::result::Result<axum_server::tls_rustls::RustlsConfig,std::io::error::Error> >::unwrap<axum_server::tls_rustls::RustlsConfig,std::io::error::Error>
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235\library\core\src\result.rs:1107
   4: axum_admin::main::async_block$0
             at .\bin\src\main.rs:78
   5: core::future::from_generator::impl$1::poll<enum$<axum_admin::main::async_block_env$0> >
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235\library\core\src\future\mod.rs:91
   6: tokio::park::thread::impl$5::block_on::closure$0<core::future::from_generator::GenFuture<enum$<axum_admin::main::async_block_env$0> > >
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\park\thread.rs:263
   7: tokio::coop::with_budget::closure$0<enum$<core::task::poll::Poll<tuple$<> > >,tokio::park::thread::impl$5::block_on::closure_env$0<core::future::from_generator::GenFuture<enum$<axum_admin::main::async_block_env$0> > > >
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\coop.rs:102
   8: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget> >::try_with<core::cell::Cell<tokio::coop::Budget>,tokio::coop::with_budget::closure_env$0<enum$<core::task::poll::Poll<tuple$<> > >,tokio::park::thread::impl$5::block_on::closure_env$0<cor
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235\library\std\src\thread\local.rs:445
   9: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget> >::with<core::cell::Cell<tokio::coop::Budget>,tokio::coop::with_budget::closure_env$0<enum$<core::task::poll::Poll<tuple$<> > >,tokio::park::thread::impl$5::block_on::closure_env$0<core::f
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235\library\std\src\thread\local.rs:421
  10: tokio::coop::with_budget
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\coop.rs:95
  11: tokio::coop::budget
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\coop.rs:72
  12: tokio::park::thread::CachedParkThread::block_on<core::future::from_generator::GenFuture<enum$<axum_admin::main::async_block_env$0> > >
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\park\thread.rs:263
  13: tokio::runtime::enter::Enter::block_on<core::future::from_generator::GenFuture<enum$<axum_admin::main::async_block_env$0> > >
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\runtime\enter.rs:152
  14: tokio::runtime::thread_pool::ThreadPool::block_on<core::future::from_generator::GenFuture<enum$<axum_admin::main::async_block_env$0> > >
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\runtime\thread_pool\mod.rs:90
  15: tokio::runtime::Runtime::block_on<core::future::from_generator::GenFuture<enum$<axum_admin::main::async_block_env$0> > >
             at C:\Users\Jian\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.20.0\src\runtime\mod.rs:484
  16: axum_admin::main
             at .\bin\src\main.rs:27
  17: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/93ffde6f04d3d24327a4e17a2a2bf4f63c246235\library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\axum-admin.exe` (exit code: 101)
`
这个是工具链的问题吗？
