### ISSUE TITLE
安装过程出现数据库写入中文字符错误 

### ISSUE THREAD

**Issue by weiforce** [lingdu1234/axum_admin#10]
Execution Error: error returned from database: 1366 (22007): Incorrect string value: '\xE9\xA2\x84\xE8\xA7\x88...' for column `iui314`.`sys_update_log`.`title` at row 1
Execution Error: error returned from database: 1366 (22007): Incorrect string value: '\xE7\xA5\x9E\xE9\xA9\xAC' for column `iui314`.`sys_user`.`user_nickname` at row 1
表格数据初始化成功:migration/data/m20220101_000001_create_table/obj_sys_user_dept.sql
表格数据初始化成功:migration/data/m20220101_000001_create_table/obj_sys_user_post.sql
表格数据初始化成功:migration/data/m20220101_000001_create_table/obj_sys_user_role.sql
Execution Error: error returned from database: 1366 (22007): Incorrect string value: '\xE7\x94\xA8\xE6\x88\xB7...' for column `iui314`.`test_data_scope`.`data_a` at row 1

尝试对所有的sql脚本设置utf-8，只解决 部分错误 ，还是有中文无法写入。
尝试对mysql默认设置字符为utf-8,但查看mysql的iui314数据库仍然是latin1

MariaDB [(none)]> use iui314

Database changed
MariaDB [iui314]> SHOW VARIABLES LIKE 'character%';
+--------------------------+----------------------------+
| Variable_name            | Value                     |
+--------------------------+----------------------------+
| character_set_database   | latin1                |
+--------------------------+----------------------------+

**Comment by lingdu1234** [comment]
可能只能在创建数据库时，选择好数据库为UTF8,看看

**Comment by lingdu1234** [comment]
我应该也没有办法复现问题

**Comment by weiforce** [comment]
我在linux下用的是mariadb数据库，更换为mysql版本，问题解决。
应该是mariadb用的是mysql 5的老版本。更换成mysql 8问题解决。
谢谢lingdu1234
