### ISSUE TITLE
项目安装完成，登录admin帐号，大部分页面为Page not found error 404

### ISSUE THREAD

**Issue by weiforce** [lingdu1234/axum_admin#11]
队了权限查询，首页可以看到正常的内容，其它页面均为Page not found error 404

**Comment by lingdu1234** [comment]
更新了前端，数据库迁移文件忘记更新了，只更新了poemadmin那边，这边忘记了

**Comment by lingdu1234** [comment]
已经更新了sql文件 ，重新迁移数据即可，更新了文件结构，数据库中的路由路径也需要更新

**Comment by weiforce** [comment]
git更新之后，问题解决。感激。
