### ISSUE TITLE
服务过一段时间访问卡顿

### ISSUE THREAD

**Issue by RouGang** [lingdu1234/axum_admin#18]
服务过一段时间访问卡顿

**Comment by lingdu1234** [comment]
前端页面卡还是后台服务响应时间慢

**Comment by RouGang** [comment]
> 

是这种情况电脑我合上电源一段时间后。再打开后，后端服务，操作数据库的地方Failed to acquire connection from pool"所以卡死了。

**Comment by lingdu1234** [comment]
这种情况没有办法排查，可能是电脑休眠引起的，
